### PR TITLE
Complete day 5 exercise

### PR DESCRIPTION
**Pull request by amoralesch**

### CODE REVIEW

**Review by xwang1-1 — CHANGES_REQUESTED** [review]
#input statement, replace the word "How" instead of "Who"

number_letters = int(input("Who many letters would you like in your password?\n"))
number_symbols = int(input("Who many symbosl would you like?\n"))
number_numbers = int(input("Who many numbers would you like?\n"))

**Review by xwang1-1 — COMMENTED** [review]
###Is there a limit on password length?

**Comment by amoralesch** [comment]
> ###Is there a limit on password length?

I don't think there is, but it may be a good idea to have one, would you like to add that option? :)

**Comment by amoralesch** [comment]
> #input statement, replace the word "How" instead of "Who"
> 
> number_letters = int(input("Who many letters would you like in your password?\n")) number_symbols = int(input("Who many symbosl would you like?\n")) number_numbers = int(input("Who many numbers would you like?\n"))

Fixed as part of [24d3b8f](https://github.com/amoralesch/python-100days/pull/5/commits/24d3b8f75263e08d1fa0b749487227369d55e192)

**Comment by xwang1-1** [comment]
You thought you did it on purpose!!

**Review by xwang1-1 — APPROVED** [review]

**Pull request merged**
